services:
  - mongodb
  - docker

language: node

before_script:
  - sleep 15

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: echo "UNIT TEST ME"
    - name: "Integration Tests"
      script: npm run ci
    - stage: "Build"
      script:
        - docker build -t openpracticelibrary/opl-content-api .
    - stage: "Push image to Quay"
      script: bash _travis/pushToQuay.sh
      on:
        branch: master
