version: 2.1

jobs:
  build:
    working_directory: ~/opl
    docker:
      - image: node:lts
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install && npm patch
      - run:
          name: Add dependency to graphql plugin (patch)
          command: jq '.dependencies |= .+ { "@apollo/federation": "^0.15.0" }' node_modules/strapi-plugin-graphql/package.json > tmp.package.json && mv tmp.package.json node_modules/strapi-plugin-graphql/package.json
      - run:
          name: Run npm install again (patch)
          command: npm install
      - save_cache:
          key: dependency-cache{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: node:lts
      - image: mongo
    steps:
      - checkout
      - run:
          name: Test
          command: npm run ci
  workflows:
    version: 2
    build_and_test:
      jobs:
        - build
        - test:
            requires:
              - build
            filters:
              branches:
                only: master


