version: 2.1
orbs:
  jq: circleci/jq@2.0.2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:lts
      - image: circleci/mongo:latest
    steps:
      - jq/install
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            # Start: Required while Strapi fix is in PR
            - run: npm run patch
            - run: jq '.dependencies |= .+ { "@apollo/federation": "^0.15.0" }' node_modules/strapi-plugin-graphql/package.json > tmp.package.json && mv tmp.package.json node_modules/strapi-plugin-graphql/package.json
            - run: npm install
            # End: Required while Strapi fix is in PR
            - run: npm ci
workflows:
    build-and-test:
      jobs:
        - build-and-test