{{- if .Values.builds }}
{{- with .Values.builds }}
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "{{ $.Values.app_name }}-pipeline"
  namespace: {{ .namespace | default $.Values.namespace | quote }}
spec:
  nodeSelector: {}
  runPolicy: {{ .run_policy | default "Serial" | quote }}
  triggers:
    - type: "GitLab"
      gitlab:
        secretReference: "gitlab-webhook"
    - type: "ConfigChange"
  source:
    contextDir: {{ .source_context_dir | default "" | quote }}
    git:
      uri: "{{ .source_repo }}"
      ref: {{ .source_repo_ref | default "master" | quote }}
    type: Git
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfilePath: "Jenkinsfile"
status:
  lastVersion: 0
{{- end }}
{{- end }}

