{{- if .Values.deployment }}
{{ $appname := .Values.app_name }}
{{- range $dc := .Values.deployment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appname}}
  namespace: {{ $dc.namespace | default $.Values.namespace | quote }}
spec:
  replicas: {{ $dc.replicas | default "1" }}
  selector:
    matchLabels:
      app: "{{ $appname }}"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "{{ $appname }}"
      name: "{{ $appname }}"
    spec:
      containers:
      - env:
{{ toYaml $dc.env_vars | indent 8 }}
        image: "{{ $dc.image_name | default $appname }}:{{ $dc.created_image_tag }}"
        imagePullPolicy: Always
        name: "{{ $appname }}"
        ports:
{{- range $ports := $dc.ports }}
          - name: {{ $ports.name }}
            containerPort: {{ $ports.containerPort }}
            protocol: {{ $ports.protocol }}
{{- end }}
{{- if $dc.volume_mounts }}
        volumeMounts:
{{ toYaml $dc.volume_mounts | indent 8 }}
{{- end }}
{{- if $dc.volumes }}
      volumes:
{{ toYaml $dc.volumes | indent 6 }}
{{- end }}
      terminationGracePeriodSeconds: 60
{{- end }}
{{- end }}
