{{- if .Values.services }}
{{ $appname := .Values.app_name }}
{{- range $svc := .Values.services }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ $appname }}
  namespace: {{ $.Values.namespace | quote }}
spec:
  ports:
{{- range $port := $svc.ports }}
  - name: {{ $port.name }}
    protocol: {{ $port.protocol | default "TCP" | quote }}
    port: {{ $port.port }}
    targetPort: {{ $port.targetPort }}
    nodePort: 0
{{- end }}
  selector:
    deploymentConfig: {{ $appname }}
  type: {{ $svc.type }}
  sessionAffinity: None
status:
  loadBalancer: {}
{{- end }}
{{- end }}

