app_name: "opl-cms"
namespace: "opl-dev"

builds:
  created_image_tag: "0.0.1"
  trigger_type: "GitLab"
  source_repo: "https://gitlab.com/rht-opl/opl-cms.git"
  source_repo_ref: "master"
  builder_image_name: "nodejs"
  builder_image_tag: "10"

imagestreams:
  enabled: true

services:
  - ports:
      - name: http
        protocol: TCP
        port: 1337
        targetPort: 1337
    type: ClusterIP

route:
  - port:
      targetPort: 1337
    to:
      kind: Service
      name: opl-cms
      weight: 100

deploymentconfigs:
  - replicas: 1
    env_vars:
      - name: "NODE_ENV"
        value: "production"
      - name: "DATABASE_HOST"
        value: "opl-mongodb"
    ports:
        - containerPort: 1337
          name: http
          protocol: TCP
