app_name: "opl-cms"
namespace: "opl-dev"
cicd_namespace: "opl-ci-cd"

builds:
  created_image_tag: "0.0.1"
  namespace: opl-ci-cd
  trigger_type: "GitLab"
  source_repo: "https://gitlab.com/rht-opl/opl-cms.git"
  source_repo_ref: "master"
  builder_image_name: "nodejs"
  builder_image_tag: "10"
  secret_name: "gitlab-webhook"

imagestreams:
  enabled: true
  cicd: true
  namespace: opl-ci-cd

services:
  - ports:
      - name: http
        protocol: TCP
        port: 1337
        targetPort: 1337
    type: ClusterIP

route:
  port:
    targetPort: 1337
  to:
    kind: Service
    name: opl-cms
    weight: 100

deployment:
  replicas: 1
  image_name: image-registry.openshift-image-registry.svc:5000/opl-dev/opl-cms
  env_vars:
    - name: "NODE_ENV"
      value: "production"
    - name: "DATABASE_HOST"
      value: "opl-mongodb"
  ports:
    - containerPort: 1337
      name: http
      protocol: TCP
