app_name: "open-practice-library-cms"
namespace: "opl-dev"

builds:
  - name: "open-practice-library-cms"
    trigger_type: "GitHub"
    source_repo: "https://github.com/rht-labs/open-practice-library-cms.git"
    source_repo_ref: "master"
    builder_image_name: "nodejs"
    builder_image_tag: "10"

imagestreams:
  - name: open-practice-library-cms

services:
  - name: open-practice-library-cms
    ports:
      - name: http
        protocol: TCP
        port: 1337
        targetPort: 1337
    type: ClusterIP

route:
  - name: open-practice-library-cms
    namespace: opl-dev
    port:
      targetPort: 1337
    to:
      kind: Service
      name: open-practice-library-cms
      weight: 100

deploymentconfigs:
  - namespace: opl-dev
    name: open-practice-library-cms
    replicas: 1
    env_vars:
      - name: "NODE_ENV"
        value: "development"
      - name: "DATABASE_HOST"
        value: "opl-mongodb"
      - name: "DATABASE_NAME"
        value: "open-practice-library"
    ports:
        - containerPort: 1337
          name: http
          protocol: TCP
    image_version: "latest"
