name: Dev Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    services:
      mongo:
        image: mongo:latest
        ports:
        - 27017:27017

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - name: Fix Strapi GraphQL Plugin
        run: npm run patch

      - name: Fix Strapi GraphQL Plugin dependency
        run: |
          jq '.dependencies |= .+ { "@apollo/federation": "^0.15.0" }' node_modules/strapi-plugin-graphql/package.json > tmp.package.json && mv tmp.package.json node_modules/strapi-plugin-graphql/package.json

      - name: Install Strapi GraphQL Plugin dependency
        run: npm install

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-

      - name: Run Linter
        run: npm run lint

      - name: Run Unit Tests
        run: echo "Oops! We should get some of those unit test thingys in here soon..."

      - name: Run API tests
        run: npm run test:api
  build-image-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASS }}
          registry: quay.io
          repository: openpracticelibrary/opl-content-api
          tags: ${{ github.sha }}
  kustomize:
    runs-on: ubuntu-latest
    needs: build-image-and-push

    steps:
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.5.5"

      - name: Checkout cd repo
        uses: actions/checkout@v2
        with:
          repository: openpracticelibrary/opl-cd
          token: ${{ secrets.SERVICE_PAT }}

      - name: Kustomize build
        run: |
          cd openpracticelibrary/content-api/overlays/development
          kustomize edit set image quay.io/openpracticelibrary/opl-content-api:${{ github.sha }}
          git add .
          git commit -m "Automated Action: Updated opl-content-api dev image tag to `${SHA8}`"
          git push origin master


