name: Content API Prerelease

on:
  release:
    types: [prereleased]

jobs:
  rc-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout opl-content-api
        uses: actions/checkout@v2

      - name: Tag with prereleased version
        uses: tinact/docker.image-retag@1.0.2
        with:
          image_name: openpracticelibrary/opl-content-api
          image_old_tag: ${{ github.sha }}
          image_new_tag: ${{ github.event.release.tag_name }}
          registry: quay.io
          registry_username: ${{ secrets.QUAY_USER }}
          registry_password: ${{ secrets.QUAY_PASS }}

      - name: Tag with latest for future full releases
        uses: tinact/docker.image-retag@1.0.2
        with:
          image_name: openpracticelibrary/opl-content-api
          image_old_tag: ${{ github.sha }}
          registry: quay.io
          registry_username: ${{ secrets.QUAY_USER }}
          registry_password: ${{ secrets.QUAY_PASS }}

  kustomize:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.5.5"

      - name: Checkout cd repo
        uses: actions/checkout@v2
        with:
          repository: openpracticelibrary/opl-cd
          token: ${{ secrets.SERVICE_PAT }}

      - name: Kustomize build
        run: |
          cd openpracticelibrary/content-api/overlays/prerelease
          kustomize edit set image quay.io/openpracticelibrary/opl-content-api:${{ github.event.release.tag_name }}
          git config --global user.email "shahein@redhat.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Automated Action: Updated opl-content-api prerelease image tag"
          git push origin master
